### PR TITLE
fix default options overriding 

### LINKED ISSUE #6: options gets overwrite in case of multiple instances of rollup-plugin-size
`rollup-plugin-size` uses below code to extend default options [check here ](https://github.com/luwes/rollup-plugin-size/blob/bc9145f3d62a81eb56486b2dc5aaf6e3095051da/rollup-plugin-size.js#L24)

```js
const coreOptions = Object.assign(defaults, options);
```
In case of multiple instance of `rollup-plugin-size`, the options gets overwritten by the last instance's option. 

e.g 
rollup.config.js
```js
import size from 'rollup-plugin-size';
import pkg from './package.json'

export default [
  {
    input: 'src/index.js',
    output: {
      file: 'dist/index.js'
      format: 'cjs',
    },
    plugins: [ size({filename:'sizes-cjs.json'})],
  },
  {
    input: 'src/index.js',
    output: {
      file: 'dist/index.es.js'
      format: 'es',
    },
    plugins: [ size({filename:'sizes-es.json'})],
  },
]

```
above configuration only create  `sizes-es.json` file, ideally, it should create both(`sizes-es.json` & `sizes-cjs.json`) files

### PR DESCRIPTION
**Pull request by kuldeepkeshwar**
Fixes #6

### CODE REVIEW

File: rollup-plugin-size.js [hunk 1]
```diff
@@ -21,7 +21,7 @@ const defaults = {
  * @param {boolean} [options.writeFile] option to save filesizes to disk
  */
 function bundleSize(options) {
-  const coreOptions = Object.assign(defaults, options);
+  const coreOptions = Object.assign(options, defaults);
```
Comment (luwes) [inline rollup-plugin-size.js]: defaults should be overwritten by options no? 
I think we have to maintain this order `Object.assign(defaults, options)`.

mutating defaults is probably not good
maybe `Object.assign({}, defaults, options)`?

**Comment by luwes** [comment]
thanks, I'll merge and fix the spacing after the comma's

**Comment by kuldeepkeshwar** [comment]
thanks, @luwes. Sorry for messing up with formating, I was typing from mobile 😄
